# general
seed: 2020
state: INFO
use_text: True
reproducibility: True
checkpoint_dir: 'saved'
show_progress: True

log_wandb: True
wandb_project: 'REC'
MAX_ITEM_LIST_LENGTH: 10
MAX_TEXT_LENGTH: 128

data_path: ../dataset/                       # dataset path
dataset: Pixel50K                        # dataset name

text_path: text_path # Use absolute path
text_keys: ['title', 'tag', 'description']

#item_prompt: 'Compress the following sentence into embedding: '
#item_prompt: 'Compress the following sentence and image into embedding: '
#item_prompt: 'Compress the image and following sentence into embedding: '
#item_prompt: 'Compress the following sentence and image into embedding: '
item_prompt: 'Compress the following sentence and picture into embedding: '
item_emb_token_n: 1

loss: nce

# training settings
epochs: 10
train_batch_size: 16 #8->4->2
optim_args: {
  learning_rate: 1e-4,
  weight_decay: 0.01
}
scheduler_args: {
  type: cosine,
  warmup: 0.1
}

# eval settings
eval_batch_size: 256
topk: [5,10,20,50,100,200]
metrics: ['Recall', 'NDCG']
valid_metric: NDCG@200
metric_decimal_place: 7
eval_step: 1
stopping_step: 5

strategy: deepspeed
precision: bf16-mixed

# DeepSpeed 配置
deepspeed_config:
  train_batch_size: 1  # 确保这与您的 train_batch_size 一致
  fp16:
    enabled: false
  bf16:
    enabled: true
  zero_optimization:
    stage: 3
    offload_optimizer:
      device: cpu
      pin_memory: true
    offload_param:
      device: cpu
      pin_memory: true
  gradient_accumulation_steps: 1  # 如果需要梯度累积，可以增加这个值
  gradient_clipping: 1.0
  zero_allow_untested_optimizer: true
  zero_force_ds_cpu_optimizer: false  # 添加这一行
  optimizer:
    type: AdamW
    params:
      lr: 1e-4
      betas: [0.9, 0.999]
      eps: 1e-8
      weight_decay: 0.01

# 添加这个配置项
gradient_checkpointing: True  # 默认关闭，可以通过命令行参数开启
